on:
  push:
    branches:
      - main  # or specify the branches you want this to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate SBOM
      run: |
        cyclonedx-py -r -i ./requirements.txt --format json -o ./bom.json --overwrite
    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: ./bom.json

    - name: Commit SBOM to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bom.json
        git commit -m "ADD SBOM"
        git push

    - name: Upload SBOM to Portal using curl
      run: |
        curl -k -X POST "https://sbom.tssconsultancy.com:8083/api/v1/bom" \
          -H "Content-Type: multipart/form-data" \
          -H "X-Api-Key: odt_eK1yFLzxS8yEWXjUL8BFuVEOURK6864a" \
          -F "project=e23ad562-7752-48f6-9d55-330e5b9403c4" \
          -F "bom=@./bom.json"
