on: 
  push:
    branches:
      - main  # or specify the branches you want this to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate SBOM
      uses: CycloneDX/gh-python-generate-sbom@v2
      with:
        input: ./requirements.txt   # Corrected the file name ('requiremnts.txt' -> 'requirements.txt')
        output: ./bom.json
        format: json
    - name: Upload Sbom as an artifact
      uses: actions/upload-artfiact@v2
      with:
        name: SBOM
        path: ./bom.json
    - name: Commit Sbom to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add bom.json
        git commit -m "ADD SBOM"
        git push
        
