name: Generate SBOM and Upload

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main

  # Allow manual triggering through the GitHub API or UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove existing bom.json (if it exists)
      run: |
        if [ -f ./bom.json ]; then
          rm ./bom.json
        fi

    - name: Generate SBOM
      uses: CycloneDX/gh-python-generate-sbom@v2
      with:
        input: ./requirements.txt   # Correct input file path for your requirements.txt
        output: ./bom.json         # Specify where to save the generated SBOM
        format: json               # You can also specify other formats like XML

    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: ./bom.json

    - name: Commit SBOM to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bom.json
        git commit -m "ADD SBOM"
        git push
