name: Generate SBOM and Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies from existing requirements.txt, if present
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Regenerate requirements.txt
      run: |
        pip freeze > requirements.txt  # Regenerate the requirements.txt file

    - name: Check if requirements.txt has changed
      run: |
        git diff --exit-code requirements.txt || echo "requirements.txt has changed"

    - name: Commit updated requirements.txt to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add requirements.txt
        git diff --cached --quiet || git commit -m "Update requirements.txt"
        git push

    - name: Remove existing bom.json (if it exists)
      run: |
        if [ -f ./bom.json ]; then
          rm ./bom.json
        fi

    - name: Generate SBOM
      uses: CycloneDX/gh-python-generate-sbom@v2
      with:
        input: ./requirements.txt   # Input the latest requirements.txt
        output: ./bom.json         # Specify where to save the SBOM
        format: json               # You can also specify other formats like XML

    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: ./bom.json

    - name: Commit SBOM to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bom.json
        git diff --cached --quiet || git commit -m "Add SBOM"
        git push
